### ISSUE TITLE
Your Origin Portable App downloaded on individual way did delete my c:\temp with important files inside

### ISSUE THREAD

**Issue by monstertruckpa** [Port-Able/Port-Able-Suite#4]
My Temp folder on C:\temp wich always i use specially as an "Download Folder" for browsers and to extract and launch portables from zip containers and sfx executables was deleted when i click your OriginPortable64.exe  that came from inside of OriginPortable_2018-05-09_18-16-52.7z creating another temporal folder called-temp-{1724877173}.backup but completely empty, all my files on C:\TEMP has been disapperead instantly.
What about that,  I think there is a kind of stupidity dishonest or error of attributes in the development of this portable launcher, illegal commands and attributes that force the deletion of personal folders, as if it were a ransomware. 
but please I want to know if I permanently lost my files or can recover them?
I have Jdownloader and steam portable downloaded from your site, and I fear for them because I have already used them, I have not yet checked if they have destroyed other folders, now im in check process all free spaces on my disk.
Then I permanently lost my files or can recover them?

**Comment by koryboc** [comment]
You need to know that Origin is a very complicated program for portalization. Much more complicated than Steam. So I don't think that can happen when using another portable program.

Anyway, it's a very bad idea using `C:\Temp` for personal things because some programs use it for temporary installation data. Origin itself would be such an example even without portalization. Some components ignore the recommended `%TEMP%` location and use always `C:\Temp` instead.

I'm sorry if you lost any data. But I believe that the day had to come someday if using such a directory for your personal stuff. I just hope that there was no data which can't be obtained from other sources.

If you are sure that the `temp- {1724877173} .backup` folder is empty and there are no more backup folders with a similar naming scheme, the files will be lost if you use an SSD. If you use an HDD there is still hope. However, this depends on the writes that occurred after the loss. There are recovery tools like `Recuva` to recover deleted files.

However, in the future, I will address such issues and implement ways to handle and avoid these specific cases. Thank you for your report.

**Comment by monstertruckpa** [comment]
The data was lost without an opportunity to do anything, but the true strange fact is that your program has deleted all contents of the mother directory "C:\TEMP" and its contents from the root without alerts, when in the past no other program had caused a similar problem or such of magnitude.
for example: "C:\TEMP\Origin (portable)\ OriginPortable.exe" where the guilty executable, which is in the folder "Origin (Portable)" should not delete what does not correspond "all the previous directory paths of the temporary "C:\TEMP, it should only delete C:\Temp\Origin (portable)\ and its contents if he needs to do maintenance himself.
A total devastation.
C:\TEMP\PotPlayer (Portable)
C:\TEMP\TonsOfM3U8TvPlaylist\
C:\TEMP\VCredistUpdates\
C:\TEMP\My Personal Ext for Chromium\
C:\TEMP\IDM\Downloads\
C:\TEMP\QBittorrent (Portable)\Downloads\
C:\TEMP\Instagram Backups\
and many more.
The TEMP folder I have always created it  by myself with my own hands, windows has not created or installed anything in that folder. On my computer Microsoft Windows only use the folders "C:\Windows\Temp" and the Users can use "C:\Users\ExampleUser***\AppData\Local\Temp" to extract temporarily files and keep the garbage a few days, My "C:\TEMP" was never affected. Your program is a garbage that violates the rules of the system with high attrib /f command privelegies, Even Ccleaner, Wise365, Tuneup, Kerish Doctor, Bleachbit or other programs have not touch that folder.
